GET http://localhost:3000/users

###
GET http://localhost:3000/users/Mike

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Mike",
    "password": "secret123"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Mike",
    "password": "secret123"
}
###
POST http://localhost:3000/validate
Content-Type: application/json

{
    "email": "james@james.com",
    "town": "Vilnius",
    "age": 25,
    "gender": "male"
}

###
GET http://localhost:3000/posts
###
GET http://localhost:3000/posts/category/4
###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa2UiLCJpYXQiOjE2NDY3NDYwMTMsImV4cCI6MTY0Njc0OTYxM30.YVZmGESJ4vqqAQBaVXRYkzDN2cVi9wJ6BK0qJLzNqpk

{
    "title": "TEST POST TITLE",
    "body": "TEST BODY",
    "category_id": 3
}
